Repository wecode-bootcamp-korea/27-1st-ZARANARA-backend, pull requests merged in 2021-12, with the labels that each got.

#1 [자라나라] 테이블 작성
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  zara/settings.py
Labels: Status: 리뷰 요청

#2 Feature/model
  .gitignore
  orders/migrations/0002_rename_stock_orderproduct_product_option.py
  orders/models.py
  products/migrations/0002_auto_20211201_2135.py
  products/models.py
  users/migrations/0002_rename_stock_cart_product_option.py
  users/migrations/0003_alter_user_password.py
  users/models.py
Labels: Status: Accepted

#3 Modified: products.models add productset table
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20211201_2135.py
  products/migrations/0002_auto_20211203_1650.py
  products/models.py
Labels: Status: 리뷰 요청

#4 마이그레이션파일 버그 수정
  orders/migrations/0001_initial.py
  orders/migrations/0002_rename_stock_orderproduct_product_option.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20211203_1650.py
  users/migrations/0001_initial.py
  users/migrations/0002_rename_stock_cart_product_option.py
  users/migrations/0003_alter_user_password.py
Labels: Status: Accepted

#7 [Create] signup views.py(회원가입) 작성
  users/urls.py
  users/validation.py
  users/views.py
  zara/urls.py
Labels: Status: Accepted

#10 [CREATED] 로그인 views.py 작성
  users/urls.py
  users/views.py
  zara/settings.py
Labels: Status: 리뷰 요청

#9 [CREATED] 로그인 decorator 작성
  core/utils.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: Conflict 해결 요청

#5 [CREATED] products앱 상세 페이지 detailview 작성
  core/utils.py
  products/models.py
  products/urls.py
  products/views.py
  users/views.py
  zara/urls.py
  zaranara.sql
Labels: Status: 리뷰 요청

#12 products 앱의 ProductSetListView, ProductListview 작성
  .gitignore
  products/models.py
  products/urls.py
  products/views.py
  zaranara.sql
Labels: Status: 리뷰 요청

#14 Feature/login decorator
  users/validation.py
  users/views.py
Labels: Status: 리뷰 요청

#13 [CREATED] 세트상품 상세이미지 _ SetProductView
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#16 [CREATED] 좋아요 토글 기능 추가 _ LikeToggleView
  products/models.py
  products/urls.py
  products/views.py
Labels: Status: Accepted

#17 User 앱 장바구니 기능 구현 및 모델링 수정
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/models.py
  users/migrations/0001_initial.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#20 [modify] ProductView :: remove -> color // add -> size.information
  products/views.py
Labels: Status: 리뷰 요청

#19 User 앱 장바구니 기능 구현 및 모델링 수정
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/models.py
  users/migrations/0001_initial.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#21 User앱의 CartView 및 모델 수정 // Products앱의 ProductSetView 수정
  .gitignore
  products/views.py
  users/migrations/0002_alter_cart_product.py
  users/models.py
  users/views.py
Labels: Status: Accepted
